CREATE TABLE [dbo].[DateReport] (
    [ID]                     INT            IDENTITY (1, 1) NOT NULL,
    [Date]                   DATETIME       NOT NULL,
    [CreateBy]               NVARCHAR (256) NULL,
    [Status]                 INT            CONSTRAINT [DF_DateReport_Status1] DEFAULT ((0)) NULL,
    [TotalAmount]            FLOAT (53)     NULL,
    [FinalAmount]            FLOAT (53)     NULL,
    [Discount]               FLOAT (53)     NULL,
    [DiscountOrderDetail]    FLOAT (53)     NULL,
    [TotalCash]              FLOAT (53)     CONSTRAINT [DF_DateReport_TotalCash] DEFAULT ((0)) NULL,
    [TotalOrder]             INT            NOT NULL,
    [TotalOrderAtStore]      INT            NOT NULL,
    [TotalOrderTakeAway]     INT            NOT NULL,
    [TotalOrderDelivery]     INT            NOT NULL,
    [TotalOrderDetail]       FLOAT (53)     NOT NULL,
    [TotalOrderFeeItem]      FLOAT (53)     NOT NULL,
    [TotalOrderCard]         INT            NOT NULL,
    [TotalOrderCanceled]     INT            NULL,
    [TotalOrderPreCanceled]  INT            NULL,
    [FinalAmountAtStore]     FLOAT (53)     NULL,
    [FinalAmountTakeAway]    FLOAT (53)     NULL,
    [FinalAmountDelivery]    FLOAT (53)     NULL,
    [FinalAmountCard]        FLOAT (53)     NULL,
    [FinalAmountCanceled]    FLOAT (53)     NULL,
    [FinalAmountPreCanceled] FLOAT (53)     NULL,
    CONSTRAINT [PK_DateReport] PRIMARY KEY CLUSTERED ([ID] ASC)
);

