CREATE TABLE [dbo].[OrderDetail] (
    [OrderDetailID]                 INT            IDENTITY (1, 1) NOT NULL,
    [OrderId]                       INT            NOT NULL,
    [ProductId]                     INT            NOT NULL,
    [ProductCode]                   NVARCHAR (50)  NOT NULL,
    [ProductName]                   NVARCHAR (500) NULL,
    [FinalAmount]                   FLOAT (53)     NOT NULL,
    [TotalAmount]                   FLOAT (53)     NOT NULL,
    [Discount]                      FLOAT (53)     NOT NULL,
    [Quantity]                      INT            NOT NULL,
    [OrderDate]                     DATETIME       NOT NULL,
    [Status]                        INT            NOT NULL,
    [Notes]                         NVARCHAR (250) NULL,
    [TaxValue]                      FLOAT (53)     NULL,
    [UnitPrice]                     FLOAT (53)     NOT NULL,
    [ProductType]                   INT            NULL,
    [ParentId]                      INT            NULL,
    [ProductOrderType]              INT            NOT NULL,
    [ItemQuantity]                  INT            NOT NULL,
    [OrderGroup]                    INT            NOT NULL,
    [TmpDetailId]                   INT            NULL,
    [PromotionCode]                 NVARCHAR (250) NULL,
    [OrderPromotionMappingId]       INT            NULL,
    [OrderDetailPromotionMappingId] INT            NULL,
    [Active]                        BIT            NULL,
    [Code]                          NVARCHAR (30)  NULL,
    [PrintGroup]                    INT            NULL,
    CONSTRAINT [PK_OrderDetail] PRIMARY KEY CLUSTERED ([OrderDetailID] ASC),
    CONSTRAINT [FK_OrderDetail_Order] FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Order] ([OrderId]) ON DELETE CASCADE
);

